name: CI
kind: pipeline
type: docker

steps:
  - name: install
    image: khs1994/php:7.4.0-composer-alpine
    commands:
    - pwd
    - composer install
    # - composer update

  - name: script
    pull: always
    image: khs1994/php:7.4.0-fpm-alpine
    environment:
      CI_REDIS_HOST: redis
      CI_REDIS_PORT: 6379
      CI_MYSQL_HOST: mysql
      CI_MYSQL_PORT: 3306
      CI_MYSQL_USERNAME: root
      CI_MYSQL_PASSWORD: test
      CI_MYSQL_DATABASE: test
    commands:
      - pwd
      - mv $${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini.default $${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini
      - sleep 30
      - vendor/bin/phpunit --coverage-clover=coverage.xml
    # volumes:
    # - /tmp:/tmp
    # privileged: true
    when:
      branch: master
      event: [push,pull_request,tag]

   - name: codecov
     image: plugins/codecov
     settings:
       # token: your-codecov-token
       files:
       - "*.xml"
       paths:
       - tests/output/coverage
     when:
       status: success
     environment:
       CODECOV_TOKEN:
         from_secret: codecov_token

    - name: docker build
      image: plugins/docker
      settings:
        registry: docker.khs1994.com
        repo: pcit/pcit
        tags: latest
      when:
        status: success
        event: push
      environemnt:
        DOCKER_USERNAME:
          from_secret: docker_username
        DOCKER_PASSWORD:
          from_secret: docker_password

services:
  - name: mysql
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test

  - name: redis
    image: redis:6.0.2-alpine
    commands: ["--bind","0.0.0.0"]
