#
# @see https://github.com/khs1994-php/khsci/blob/master/docs/SUMMARY.md
#

language: php

clone:
  git:
    # image: plugins/git
    depth: 10
    # recursive: true
    # skip_verify: false
    # tags: false
    # submodule_override:
      # hello-world: https://github.com/octocat/hello-world.git
    hosts:
      git.t.khs1994.com: 192.168.199.100

workspace:
  base: /app
  # path: .
  path: src

cache:
  directories:
  - vendor
  - .php_cs.cache

pipeline:
  #
  # This is phpunit demo
  #

  php:
    image: khs1994/php-fpm:${PHP_VERSION}
    pull: true
    environment:
      - CI_REDIS_HOST=redis
      - CI_REDIS_PORT=6379
      - CI_MYSQL_HOST=mysql
      - CI_MYSQL_PORT=3306
      - CI_MYSQL_USERNAME=root
      - CI_MYSQL_PASSWORD=mytest
      - CI_MYSQL_DBNAME=test
    commands:
      - mv ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini.default ${PHP_INI_DIR}/conf.d/docker-php-ext-xdebug.ini
      - env
      - pwd
      - composer install
      - composer update
      # 服务初始化需要时间，这里延迟执行
      - sleep 30
      - vendor/bin/phpunit --coverage-clover=coverage.xml
      # set env CODECOV_TOKEN=XXX
      # - bash <(curl -s https://codecov.io/bash)
    when:
      # platform: linux/amd64
      # platform:  [ linux/*, windows/amd64 ]

      # status: changed
      # status:  [ failure, success ]

      # event: tag
      # event: [push, pull_request, tag, deployment]
      event: [push, pull_request, tag]

      # branch: master
      # branch: prefix/*
      # branch: [master, develop]
      # branch:
      #   include: [ master, release/* ]
      #   exclude: [ release/1.0.0, release/1.1.* ]
      # tag: 7.1.*

      # ^[0-9.]+$     1.2.0
      # ^[0-9.]+      1.2.0-rc
      # ^v([0-9.]+)$  v1.2.3


  #
  # This is a build docker image demo，when tag push
  #

  publish_php:
    #
    # ci_xxx KhsCI Image
    #
    image: ci_docker_build
    # registry: docker.khs1994.com
    repo: khs1994/php-fpm
    tags: swarm-7.2.5-${CI_TAG}
    # target: php
    build_args:
       - a:1
    # dockerfile: Dockerfile
    # dockerfile: path/to/Dockerfile
    when:
      event: tag
    environment:
      - DOCKER_USERNAME=username
      - DOCKER_PASSWORD=password

  #
  # This is success after demo
  #

  success:
    image: khs1994/tencent_cloud_cos:v4
    when:
      status: success
    file:
      README.md: khsci/tencent_cloud_cos_file_name_${KHSCI_TAG}
      Dockerfile: khsci/tencent_cloud_cos_file_name2_${KHSCI_TAG}
    # please set env by khsci env_var feature,don't set secret in .khsci.yml
    # environment:
      # - COS_REGION=x
      # - COS_APP_ID=x
      # - COS_SECRET_ID=x
      # - COS_SECRET_KEY=x
      # - COS_BUCKET=x

  #
  # This is failure after demo
  #

  failure:
    image: khs1994/email
    when:
      status: failure

  #
  # This is build status changed demo,example prev success current failure
  #

  changed:
    image: khs1994/email
    when:
      status: changed

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=mytest
    # entrypoint: [ "mysqld" ]
    command: [ "--character-set-server=utf8mb4", "--default-authentication-plugin=mysql_native_password" ]

  # postgresql:
  #   image: postgres:${POSTGRESQL_VERSION}
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=test

  redis:
    image: redis:${REDIS_VERSION}
    command: ["--bind", "0.0.0.0"]

  # mongodb:
  #   image: mongo:${MONGODB_VERSION}
  #   command: [ --smallfiles ]

matrix:
  PHP_VERSION:
    - 7.2.6-alpine3.7
    - 7.1.18-alpine
    # - 7.1.17-alpine3.4
    # - 7.0.30-alpine3.4
    # - 5.6.36-alpine3.4
  NGINX_VERSION:
    - 1.13.12
  REDIS_VERSION:
    - 4.0.9-alpine
  MYSQL_VERSION:
    # - 8.0.11
    - 5.7.22
  MONGODB_VERSION:
    - 3.7.3
  POSTGRESQL_VERSION:
    - 10.3-alpine

branches:
  include: [ master ]
  exclude: test*
  # include: [ master, release/* ]
  # exclude: [ release/1.0.0, release/1.1.* ]

config:
  aliyun:
    docker_registry:
      # registry: git_repo_full_name
      khs1994/wsl: khs1994-php/khsci

  tencent_cloud:
    docker_registry:
      khs1994/wsl: khs1994-php/khsci

  mirrors:
    - git@git.coding.net:khs1994/khsci.git
    - https://gitee.com/khs1994-php/khsci.git
    - git@code.aliyun.com:khs1994-php/khsci.git
