version: "3.7"

services:

  pcit:
    image: pcit/pcit:alpine
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - PHP_VERSION=${PHP_VERSION:-7.4.0}
        - NODE_VERSION=${NODE_VERSION:-12.9.0}
        - NODE_REGISTRY=https://registry.npm.taobao.org

  all:
    &all
    image: pcit/pcit:alpine
    command: up

  server:
    << : *all
    command: server

  agent:
    << : *all
    command: agent

  gc:
    << : *all
    command: gc
