version: "3.7"

services:

  pcit:
    image: pcit/pcit
    build:
      context: .
      dockerfile: Dockerfile
      target: pcit
      args:
        - PHP_VERSION=${PHP_VERSION:-7.4.6}
        - NODE_VERSION=${NODE_VERSION:-14.2.0}
        - NODE_REGISTRY=https://registry.npm.taobao.org

  all:
    &all
    image: pcit/pcit
    command: up

  server:
    << : *all
    command: server

  agent:
    << : *all
    command: agent
