name: Build Image

on: push

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: git clone --depth=1 https://github.com/pcit-ce/ui frontend
      - run: docker buildx build -t pcit/pcit:alpine -t pcit/pcit --target=php --push .
