name: Build Image

on: push

jobs:
  build_image:
    runs-on: ubuntu-latest
    if: |
      contains( github.event.head_commit.message, '[build image]')
      || contains( github.ref, 'refs/tags/')
    steps:
      - uses: azure/docker-login@v1
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: git clone --depth=1 https://github.com/pcit-ce/ui frontend
        name: Clone frontend
      - run: |
          set -x

          TAG=`echo $GITHUB_REF | cut -d '/' -f 3`
          docker buildx build \
            -t pcit/pcit \
            -t pcit/pcit:${TAG} \
            -t pcit/pcit:server \
            -t pcit/pcit:${TAG}-server \
            -t pcit/pcitd \
            -t pcit/pcitd:${TAG} \
            -t pcit/server \
            -t pcit/server:${TAG} \
            --platform ${PLATFORM} \
            --target=pcit --push .

          docker buildx build \
            -t pcit/pcit:cli \
            -t pcit/pcit:${TAG}-cli \
            -t pcit/cli \
            -t pcit/cli:${TAG} \
            --platform ${PLATFORM} \
            --target=pcit_cli --push .

          docker buildx build \
            -t pcit/pcit:fpm \
            -t pcit/pcit:${TAG}-fpm \
            -t pcit/fpm \
            -t pcit/fpm:${TAG} \
            --platform ${PLATFORM} \
            --target=pcit_fpm --push .

          docker buildx build \
            -t pcit/pcit:unit \
            -t pcit/pcit:${TAG}-unit \
            -t pcit/unit \
            -t pcit/unit:${TAG} \
            --platform ${PLATFORM} \
            --target=unit --push .

          docker buildx build \
            -t pcit/pcit:frontend \
            -t pcit/pcit:${TAG}-frontend \
            -t pcit/frontend \
            -t pcit/frontend:${TAG} \
            --platform ${PLATFORM} \
            --target=frontend --push .
        env:
          GITHUB_REF: ${{github.ref}}
          PLATFORM: linux/amd64,linux/arm64
        name: Build image
      - run: docker run -i --rm --entrypoint=sh pcit/pcit -c "ls -la /app/pcit"
        name: List files
      - name: Test image
        run: |
          set -x

          echo docker run -i --rm pcit/pcit list > /dev/null

          docker run -i --rm pcit/pcit:cli list

          docker run -i --rm -v $PWD/dist:/var/www/pcit/public pcit/pcit:frontend
          ls -la dist
