name: Build Image

on: push

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          # login-server: contoso.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push'
      - uses: docker-practice/actions-setup-docker@master
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - run: git clone --depth=1 https://github.com/pcit-ce/ui frontend
        name: Clone frontend
      - run: |
          set -x

          TAG=`echo $GITHUB_REF | cut -d '/' -f 3`
          docker buildx build \
            -t pcit/pcit \
            -t pcit/pcit:${TAG} \
            --target=pcit --push .

          docker buildx build \
            -t pcit/pcit:frontend \
            -t pcit/pcit:${TAG}-frontend \
            -t pcit/frontend \
            -t pcit/frontend:${TAG} \
            --target=frontend --push .
        env:
          GITHUB_REF: ${{github.ref}}
        name: Build image
      - run: docker run -i --rm --entrypoint=sh pcit/pcit -c "ls -la /app/pcit"
        name: List files
      - name: Test image
        run: |
          echo docker run -i --rm pcit/pcit list > /dev/null

          set -x

          docker run -i --rm --entrypoint=/app/pcit/bin/pcit pcit/pcit list

          docker run -i --rm -v $PWD/dist:/var/www/pcit/public pcit/pcit:frontend
          ls -la dist
