on:
  push:

name: Sync Git

jobs:
  sync-git:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: sync-plugin-storage-tencent-cos-v5
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-ce/plugin-tencent-cos-v5
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/storage/tencent_cos_v5
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-plugin-storage-tencent-cos-v4
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-ce/plugin-tencent-cos-v4
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/storage/tencent_cos_v4
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-plugin-storage-s3
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-ce/plugin-s3
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/storage/s3
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-plugin-pages
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-ce/plugin-pages
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/pages
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-plugin-git
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-ce/plugin-git
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/git
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-plugin-docker
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-ce/plugin-docker
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/docker
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
    - name: sync-plugin-github-release
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/pcit-plugins/github-release
        PCIT_KEEP_HISTORY: "true"
        PCIT_LOCAL_DIR: plugins/releases/github
        PCIT_MESSAGE: Sync from pcit-ce/pcit@${{github.sha}} by PCIT
        PCIT_TARGET_BRANCH: master
        PCIT_USERNAME: khs1994
